networks:
  net:
services:
  graphql-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ${PWD}/data/data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - net
  graphql-redis:
    image: redis:7
    container_name: graphql-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
    networks:
      - net
  graphql-kafka:
    image: bitnami/kafka:latest # https://github.com/bitnami/containers.git
    user: root
    ports:
      - 9092:9092
    environment:
      - BITNAMI_DEBUG=true
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      # - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - ./Kafka:/bitnami/kafka
    networks:
      - net
    # depends_on:
    #   - zookeeper
